---
  header_logo_url:  http://Psocodea.archive.speciesfile.org/HomePage/Psocodea/img_Logo/SiteLogo.jpg
  header_logo_text: Psocodea Species File
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
