---
  header_logo_url:  https://sfg.taxonworks.org/s/e7uqdh
  header_logo_text: Psocodea Species File
  header_links:
    - label: Home
      link: /

    - label: Bibliography
      link: /resources/tw/filter/bibliography

    - label: About
      link: /about
