---
metadata:
  - name: description
    content: The Psocodea Species File is a taxonomic, nomenclatural, and bibliographic database of the lice and booklice of the world, including all extant and fossil taxa.
  - name: keywords
    content: taxonomy, species, Species File Group, taxonpages, lice, booklice, parasitic lice, Phthiraptera, Psocodea Species File
  - name: robots
    content: follow
