---
  project_name: "Psocodea Species File"
  project_citation: "Kevin P. Johnson, Vincent S. Smith, Heidi Hopkins. Psocodea Species File. Version 5.0/5.0. [retrieval date]. <http://Psocodea.SpeciesFile.org>"
  project_authors: "Johnson, K.P., Smith, V.S. & Hopkins, H."
  project_url: "https://psocodea.speciesfile.org"
  project_old_url: "http://psocodea.archive.speciesfile.org" 
  focal_taxon: "psocodea"
  focal_taxon_common_name: "lice and booklice"
  contact_email: "cockroachdoc@gmail.com"
