issue_trackers:
  - label: Data
    description: Missing data, misspellings or typos, invalid data, or you'd like to get involved
    url: https://www.github.com/sfg-taxonpages/psocodea/issues

  - label: Website
    description: A link, panel, or other feature is not working as expected, or you'd like to suggest a new feature
    url: https://www.github.com/SpeciesFileGroup/taxonpages/issues
